@startuml
skinparam classAttributeIconSize 0

abstract class User {
  +id: int
  +name: String
  +email: String
  +address: String
  +phone: String
  +role: String
  --
  +register()
  +login()
  +updateData()
}

class Client {
  +loyaltyPoints: int
}

class Admin {
  +logAction()
}

User <|-- Client
User <|-- Admin

class Product {
  +id: int
  +name: String
  +description: String
  +price: double
  +stockQuantity: int
  --
  +create()
  +update()
  +delete()
}

class Category {
  +id: int
  +name: String
}

Category "1" -- "many" Product

class Order {
  +id: int
  +createdAt: Date
  +status: String
  +totalAmount: double
  --
  +placeOrder()
  +cancel()
  +pay()
}

Client "1" -- "many" Order
Order "many" -- "many" Product

class Payment {
  +id: int
  +type: String
  +amount: double
  +status: String
  +date: Date
  --
  +process()
  +refund()
}

Order "1" -- "1" Payment


class Delivery {
  +id: int
  +address: String
  +status: String
  +courier: String
  --
  +send()
  +track()
  +complete()
}

Order "1" -- "1" Delivery

class Review {
  +id: int
  +rating: int
  +comment: String
}

Client "1" -- "many" Review
Product "1" -- "many" Review

interface PaymentAPI {
  +sendPayment()
}

PaymentAPI .. Payment

@enduml
